insert into permissions (permission) values ('Admin'),
                                            ('Can create projects'),
                                            ('Can edit projects'),
                                            ('Can delete projects'),
                                            ('Can create tasks'),
                                            ('Can edit tasks'),
                                            ('Can delete tasks'),
                                            ('Can log time'),
                                            ('Can edit log'),
                                            ('Can delete log');